# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, b'Private'), (2, b'Public')]),
        ),
    ]
