# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-05 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0003_auto_20170905_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
