# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-05 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0004_tenant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 10, 49, 13, 815517)),
        ),
    ]
